ARG APP_BUILD_ROOT=/opt/app-root

FROM registry.redhat.io/ubi9/go-toolset:1.26.5@sha256:444e81b3e88d8a68b92a081a7b3abc7d3fed2450f8473ea6b3caebf3bb73a0b8 AS builder

ARG TARGETOS
ARG TARGETARCH
ARG APP_BUILD_ROOT

ENV GOEXPERIMENT=strictfipsruntime
ENV APP_ROOT=$APP_BUILD_ROOT
ENV GOPATH=$APP_ROOT

WORKDIR $APP_ROOT/src/
COPY go.mod ./
COPY go.sum ./
COPY cmd/main.go cmd/main.go
COPY internal/ internal/
RUN go mod download && \
    CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} GOEXPERIMENT=${GOEXPERIMENT} go build -a -o ${APP_ROOT}/manager cmd/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8-1788939036@sha256:d235f607e1d6d833f031db107dc42206e4dd4d5aa9142c43d3771fb7f9bea76a AS deploy

ARG APP_BUILD_ROOT

WORKDIR /
COPY --from=builder ${APP_BUILD_ROOT}/manager .
COPY LICENSE /licenses/license.txt
USER 65532:65532

ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-workload-variant-autoscaler-controller-rhel9" \
      name="rhoai/odh-workload-variant-autoscaler-controller-rhel9" \
      description="a Kubernetes controller that performs intelligent autoscaling for inference model servers based on saturation" \
      summary="odh-workload-variant-autoscaler-controller" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-workload-variant-autoscaler-controller" \
      io.k8s.description="odh-workload-variant-autoscaler-controller" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"