name: Check Signed Commits
on: pull_request_target

jobs:
  signed-commits:
    uses: llm-d/llm-d-infra/.github/workflows/reusable-signed-commits.yaml@5ecec2569298087cda0a99669632c1fa707002c9 # main
    permissions:
      contents: read
      pull-requests: write
